### ISSUE TITLE
Title(s) not in .json file

### ISSUE THREAD

**Issue by N3tt3rm4n** [muonium/translations#2]
On each version of the website, the "KEEP OUR PRIVCACY" thing stays English, same as the "Features" title:
![grafik](https://cloud.githubusercontent.com/assets/25689289/24150924/8fb85542-0e47-11e7-861f-758852c5c19d.png)
![grafik](https://cloud.githubusercontent.com/assets/25689289/24150985/c15c413a-0e47-11e7-84fa-3b0d539b05b3.png)

and the title of the site, too:

![grafik](https://cloud.githubusercontent.com/assets/25689289/24151132/21639506-0e48-11e7-9c8d-fbace571c423.png)

Wouldn't it be a good idea to export these into the .json file so each language version of the website has its on titles?

<sup>Btw the Spanish versions seems not to be finished</sup>

**Comment by Super-Baleine** [comment]
@hitoshi54 would you take over this task please? (use the global section of json strings for titles please?)

Hey,
Yeah, Spanish translation isn't done yet, but still, even if a translation isn't finished, we put it publicly x)

**Comment by Super-Baleine** [comment]
I put "FEATURES" in json files, that's done.

**Comment by Super-Baleine** [comment]
I reopen cuz we haven't put tiles in json yet.

**Comment by N3tt3rm4n** [comment]
ok thaught it has been done^^

**Comment by Super-Baleine** [comment]
ahah, yea no x)
We'll do it soon, don't worry x)

**Comment by dclement8** [comment]
Done ;)
