### ISSUE TITLE
Translation of quote on home page

### ISSUE THREAD

**Issue by N3tt3rm4n** [muonium/translations#28]
When you access muonium.io you see that quote/orWhateverItIs "LET'S KEEP OUR PRIVACY", it would be good to translate this in each particular language since as first thing you see on the website it has some representation effect...

BTW I think LET'S KEEP OUR PRIVACY! whithout quotation marks and whith exclamation mark would be better

**Comment by Super-Baleine** [comment]
Ahah, but translating it wouldn't sound cool, right? :)

And for the quote, it's not a quote... It's more an energetic sentence to say let's do it x)
