### ISSUE TITLE
Weird (and outdated) policy spanish translation

### ISSUE THREAD

**Issue by victorhck** [muonium/translations#32]
The text in Eglish says:
"Internet privacy is a right. Why should we accept what we wouldn't accept in our daily life (offline)? For many years, private companies such as Google, Facebook, etc... as well as government agencies spy on us to gather informations about us everyday on the web. However, we are able to counter this mass spying using cryptography but not enough projects allow us to protect ourselves properly. But today, we are fortunate to have a safe alternative for our email: <span>ProtonMail</span>, which allows end-to-end encryption. Also, you can use <span>Ring.cx</span> or <span>Tox.chat</span> to encrypt your conversations.<br>It's in this perspective that we launched the development of <span>Muonium</span>, to offer an alternative for storing your documents online securely. Our policy requires us to end-to-end encrypt files making you the only true owner of your files."

More accurate translation must be:
"La privacidad en internet es un derecho. ¿Por qué deberíamos aceptar algo que no aceptaríamos en nuestra vida diaria (fuera de internet)? Durante muchos años, empresas privadas como Google o Facebook, etc... y también agencias estatales nos han espiado para conseguir información de nosotros cada día en internet. Sin embargo, podemos contrarestar este espionaje masivo utilizando criptografía, pero no hay suficientes proyectos que nos permitan protegernos de manera adecuada. Pero hoy en día somos afortunados de tener alternativas seguras para el correo electrónico: <span>ProtonMail</span>, que permite el cifrado de extremo a extremo. También puede utilizar <span>Ring.cx</span> o <span>Tox.chat</span> para cifrar sus conversaciones. <br>Es con esta perspectiva con la que hemos lanzado el desarrollo de <span>Muonium</span>, para ofrecer una alternativa de almacenamiento de sus documentos de manera segura. Nuestra política nos exige cifrar los archivos de extremo a extremo, siendo así usted en el único verdadero propietario de los mismos."

**Comment by Super-Baleine** [comment]
hahah, thanks! I'm going to change this! Next time, do not hesitate to open a pull request! :)

**Comment by Super-Baleine** [comment]
Fixed and deployed, thanks again!
