### ISSUE TITLE
Group chat for translations

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/translations#36]
Hi all,

You can now join our translations project group chat there: https://t.me/mui_localizations !

**Comment by victorhck** [comment]
sad that I don't use Telegram or Whatsapp... :(

**Comment by Super-Baleine** [comment]
What would you use for a community group chat then? :)

--
Paul Feuvraux - [ProtonMail](http://protonmail.com) infrastructure

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by w3d0wn** [comment]
How about slack?

**Comment by Super-Baleine** [comment]
Well, we care about privacy, so we should use a privacy-related service at least :)

**Comment by victorhck** [comment]
if I didn't answer it wasn't due a lack of interest in the topic, but I though that I'm just a simple geek that made a translation. I think that should answer the "core" of translation team! ;)

**Comment by Super-Baleine** [comment]
This issue was actually for everyone :)
