### ISSUE TITLE
i want to translate it into Korean

### ISSUE THREAD

**Issue by Rapha0814** [muonium/translations#49]
Hi, I'm trying to translate this project into Korean, can I?

**Comment by Super-Baleine** [comment]
Hi,

For sure you can! Tell me if you need any help in order to get started!

--
Paul Feuvraux - [ProtonMail](http://protonmail.com) infrastructure team

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Super-Baleine** [comment]
I'm closing the issue, but feel free to ask us anything from here.
